name:                midpoint-clicker
version:             0.1.0.0
github:              "kpinter3-14/midpoint-clicker"
license:             AllRightsReserved
author:              "Krisztian Pinter"
maintainer:          "kpinter3.14@gmail.com"
copyright:           "2021 Krisztian Pinter"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kpinter3-14/midpoint-clicker#readme>

default-extensions:
- BlockArguments
- LambdaCase

dependencies:
- base >= 4.7 && < 5
- containers
- gloss

executables:
  midpoint-clicker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
